<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
	<AssemblyName>OSAKA</AssemblyName>
	<Product>OSAKA</Product>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<UseWPF>true</UseWPF>
	  <ApplicationIcon>images\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\user\.nuget\packages\naudio.vorbis\1.5.0\contentFiles\any\netstandard2.0\README.md" />
    <None Remove="images\dot.png" />
    <None Remove="images\mute_over.png" />
    <None Remove="OSAKA使い方.md" />
  </ItemGroup>




  <ItemGroup>
	<Content Include="images\logo.ico">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</Content>
	<Resource Include="images\dot.png" />
	<Resource Include="images\mute.png" />
	<Resource Include="images\mute_over.png" />
	<Resource Include="images\pause.png" />
    <Resource Include="images\comment_pause.png" />
    <Resource Include="images\comment_off.png" />
    <Resource Include="images\liveon.png" />
	<Content Include="images\dot.mp4">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
	<Content Include="OSAKA使い方.md">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
	<Content Include="images\amari*.png">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
	<Resource Include="Fonts\*.ttf" />
    <Content Include="wwwroot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="audio\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="cursor\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
	<PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Emoji.Wpf" Version="0.3.4" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.75.0.4239" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    <PackageReference Include="obs-websocket-dotnet" Version="5.0.1" />
  </ItemGroup>

</Project>
